name = "Untitled"
version = "0.1.0"
defaultTargets = ["untitled"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.29.1"

[[lean_lib]]
name = "Untitled"

[[lean_exe]]
name = "untitled"
root = "Main"
